<script setup lang="ts">
import { computed, reactive, ref, watch } from 'vue'
import { onBeforeRouteLeave, useRoute, useRouter } from 'vue-router'
import { ElButton, ElCascader, ElCheckbox, ElCheckboxGroup, ElDialog, ElInput, ElInputNumber, ElMessage, ElOption, ElSelect } from 'element-plus'
import ServicePreview from '@/components/service/ServicePreview.vue'
import { CATEGORY_TREE, REGION_OPTIONS, clone, emptyService, useCommerceStore, type Case, type Service } from '@/stores/commerce'
const c=useCommerceStore(),router=useRouter(),route=useRoute();const existing=c.data.services.find(x=>x.id===route.params.id);const form=reactive<Service>(existing?clone(existing):emptyService());const step=ref(1);const chosenParks=ref<string[]>([]);const saved=ref(JSON.stringify(form));const allowLeave=ref(false);const errors=reactive<Record<string,string>>({});const caseOpen=ref(false);const previewOpen=ref(false);const inlineCase=reactive<Case>({id:'',category:'',title:'',intro:'',cover:'',createdAt:''});const dirty=computed(()=>saved.value!==JSON.stringify(form));const headings=['基础信息','服务详情','定价与交付','提交预览'];const linkedCases=computed(()=>c.data.cases.filter(x=>form.caseIds.includes(x.id)))
onBeforeRouteLeave(()=>{if(allowLeave.value||!dirty.value)return true;return window.confirm('离开将丢失未保存内容，确认离开？')})
watch(()=>form.category,()=>{ /* 类目配置为只读演示值，订单按下单时快照保存 */ })
function addFiles(event:Event,key:'cover'|'media'|'images',limit:number,max:number){const input=event.target as HTMLInputElement;const files=Array.from(input.files||[]);const valid=files.filter(f=>{const image=['image/jpeg','image/png','image/webp'].includes(f.type);const video=key==='media'&&f.type==='video/mp4';return (key==='images'?['image/jpeg','image/png'].includes(f.type):image||video)&&f.size<=(video?50:key==='media'?10:limit)*1024*1024});if(valid.length!==files.length)ElMessage.error('文件格式或大小不符合要求');if(key==='cover'){if(valid[0]){form.cover=valid[0].name;errors.cover=''}}else{const next=[...form[key],...valid.map(x=>x.name)];if(next.length>max)ElMessage.warning(`最多上传 ${max} 个文件`);form[key]=next.slice(0,max)}input.value=''}
function validate(n:number){
  Object.keys(errors).forEach(key=>delete errors[key])
  if(n===1){
    if(form.category.split(' / ').length!==3)errors.category='请选择末级服务分类'
    if(!form.name.trim()||form.name.length>60)errors.name='请填写 1–60 字服务名称'
    if(!form.intro.trim()||form.intro.length>500)errors.intro='请填写 1–500 字服务简介'
    if(!form.cover)errors.cover='请上传服务封面'
  }
  if(n===2){
    if(!form.detail.trim())errors.detail='请填写服务详情'
    if(!form.guarantee.trim())errors.guarantee='请填写服务保障说明'
    if(form.faqs.some(x=>!x.question.trim()||!x.answer.trim()))errors.faq='请完整填写每组常见问题'
  }
  if(n===3&&(!form.specs.length||form.specs.length>3||form.specs.some(x=>!x.name.trim()||!x.point.trim()||x.price<=0||!x.unit||x.startDays<0||x.deliveryDays<1||x.deliveryDays>9999||!x.standard.trim())))errors.spec='请完整填写 1–3 个规格，价格须大于 0，交付周期为 1–9999 天'
  if(n===4&&!chosenParks.value.length)errors.parks='请至少选择一个可提交的园区'
  return Object.keys(errors).length===0
}
function next(){if(validate(step.value))step.value=Math.min(4,step.value+1)}function saveDraft(){c.saveService(form);saved.value=JSON.stringify(form);ElMessage.success('草稿已保存')}function submit(){for(let i=1;i<=4;i++)if(!validate(i)){step.value=i;return}c.saveService(form,chosenParks.value);saved.value=JSON.stringify(form);allowLeave.value=true;router.push('/service/submitted')}
function exit(){router.push('/service')}
function openCase(){Object.assign(inlineCase,{id:crypto.randomUUID(),category:form.category,title:'',intro:'',cover:'',createdAt:new Date().toISOString()});caseOpen.value=true}
function saveInlineCase(){if(!inlineCase.category||!inlineCase.title.trim()||!inlineCase.intro.trim()||!inlineCase.cover){ElMessage.error('请完整填写案例分类、标题、介绍与封面');return}c.saveCase(inlineCase);if(form.caseIds.length<6)form.caseIds.push(inlineCase.id);caseOpen.value=false;ElMessage.success('案例已创建并关联')}
function caseFile(e:Event){const f=(e.target as HTMLInputElement).files?.[0];if(!f)return;if(!f.type.startsWith('image/')||f.size>10*1024*1024){ElMessage.error('封面仅支持 ≤10MB 图片');return}inlineCase.cover=f.name}
const options=computed(()=>c.joinedParks.filter(p=>!['on_sale','reviewing'].includes(form.listings[p.id]?.status||'draft')))
</script>
<template><div class="biz-page editor"><header class="biz-head"><div><p class="biz-eyebrow">服务管理 / {{existing?'编辑服务':'发布服务'}}</p><h1>{{existing?'编辑服务':'发布服务'}}</h1><p>按步骤完成服务资料，并选择目标园区提交审核。</p></div><div class="biz-actions"><ElButton @click="exit">返回列表</ElButton><ElButton @click="saveDraft">保存草稿</ElButton></div></header><div class="biz-stepper"><span v-for="(h,i) in headings" :key="h" class="biz-step" :class="{active:step===i+1}">{{i+1}} {{h}}</span></div>
<section v-if="step===1" class="biz-section"><h2>基础信息</h2><div class="biz-grid"><label class="biz-field">服务分类 <b class="required">*</b><ElCascader :model-value="form.category?form.category.split(' / '):[]" :options="CATEGORY_TREE" filterable clearable placeholder="选择末级分类" @change="form.category=Array.isArray($event)?$event.join(' / '):''"/><small v-if="errors.category" class="field-error" role="alert">{{errors.category}}</small></label><label class="biz-field">服务名称 <b class="required">*</b><ElInput v-model="form.name" maxlength="60" show-word-limit placeholder="填写服务名称"/><small v-if="errors.name" class="field-error" role="alert">{{errors.name}}</small></label><label class="biz-field full">服务简介 <b class="required">*</b><ElInput v-model="form.intro" type="textarea" :rows="3" maxlength="500" show-word-limit/><small v-if="errors.intro" class="field-error" role="alert">{{errors.intro}}</small></label><label class="biz-field">服务封面 <b class="required">*</b><input type="file" accept="image/*" @change="addFiles($event,'cover',10,1)"/><small>{{form.cover||'JPG、PNG、WEBP · ≤10MB'}}</small><small v-if="errors.cover" class="field-error" role="alert">{{errors.cover}}</small></label><label class="biz-field">详情媒体 <small>最多 8 个</small><input type="file" multiple accept="image/*,video/mp4" @change="addFiles($event,'media',50,8)"/><small>{{form.media.join('、')||'图片 ≤10MB；MP4 ≤50MB'}}</small></label><label class="biz-field full">服务区域 <small>选填；未选择表示不限区域</small><ElCascader :model-value="form.regions.map(x=>x.split(' / '))" :options="REGION_OPTIONS" :props="{multiple:true,emitPath:true}" clearable filterable collapse-tags :max-collapse-tags="8" collapse-tags-tooltip placeholder="搜索并选择省 / 市，可多选" @change="form.regions=Array.isArray($event)?($event as string[][]).map(x=>x.join(' / ')):[]"/></label></div></section>
<section v-if="step===2" class="biz-section"><h2>服务详情</h2><div class="biz-grid"><label class="biz-field full">服务详情 <b class="required">*</b><ElInput v-model="form.detail" type="textarea" :rows="5" maxlength="5000" show-word-limit/><small v-if="errors.detail" class="field-error" role="alert">{{errors.detail}}</small></label><label class="biz-field full">服务保障说明 <b class="required">*</b><ElInput v-model="form.guarantee" type="textarea" :rows="3" maxlength="2000" show-word-limit/><small v-if="errors.guarantee" class="field-error" role="alert">{{errors.guarantee}}</small></label><label class="biz-field">服务图片 <small>最多 20 张，单张 ≤5MB</small><input type="file" accept="image/*" multiple @change="addFiles($event,'images',5,20)"/><small>{{form.images.join('、')}}</small></label></div><div class="biz-divider"/><h2>关联案例 <small class="biz-muted">最多 6 个</small></h2><div class="biz-inline"><ElSelect v-model="form.caseIds" multiple :multiple-limit="6" collapse-tags :max-collapse-tags="3" placeholder="选择店铺案例" style="width:340px"><ElOption v-for="x in c.data.cases" :key="x.id" :label="x.title" :value="x.id"/></ElSelect><ElButton @click="openCase">新建案例</ElButton></div><p v-if="linkedCases.length" class="biz-muted">已关联：{{linkedCases.map(x=>x.title).join('、')}}</p><div class="biz-divider"/><div class="biz-inline"><h2 style="margin:0">常见问题</h2><ElButton :disabled="form.faqs.length>=10" @click="form.faqs.push({question:'',answer:''})">添加问题</ElButton></div><div v-for="(faq,i) in form.faqs" :key="i" class="faq-row"><ElInput v-model="faq.question" maxlength="30" placeholder="问题（≤30 字）"/><ElInput v-model="faq.answer" maxlength="200" placeholder="回答（≤200 字）"/><ElButton @click="form.faqs.splice(i,1)">删除</ElButton></div><p v-if="errors.faq" class="field-error" role="alert">{{errors.faq}}</p></section>
<section v-if="step===3" class="biz-section"><h2>定价与交付</h2><div class="biz-grid"><div class="biz-field">平台分账比例 <ElInput model-value="10%（演示配置）" disabled/></div><div class="biz-field">售后期 <ElInput model-value="7 个自然日（演示配置）" disabled/></div><label class="biz-field">发票税率 <ElSelect v-model="form.taxRate"><ElOption v-for="n in [0,1,6,9,13]" :key="n" :label="`${n}%`" :value="n"/></ElSelect></label></div><p class="biz-note">平台按服务所属末级类目的配置收取平台费；售后期自验收完成起算。售后期结束且无未解决售后时进入结算。以上比例与天数是演示配置。</p><div class="biz-divider"/><div class="biz-inline"><h2 style="margin:0">服务规格</h2><ElButton :disabled="form.specs.length>=3" @click="form.specs.push({name:'',point:'',price:0,unit:'项',startDays:0,dayType:'自然日',deliveryDays:1,standard:''})">添加规格</ElButton><span class="biz-muted">一次性付款 · 一次性验收</span></div><p v-if="errors.spec" class="field-error" role="alert">{{errors.spec}}</p><section v-for="(s,i) in form.specs" :key="i" class="spec-block"><div class="biz-inline"><strong>规格 {{i+1}}</strong><ElButton v-if="form.specs.length>1" text type="danger" @click="form.specs.splice(i,1)">删除</ElButton></div><div class="biz-grid"><label class="biz-field">规格名称 <ElInput v-model="s.name" maxlength="30"/></label><label class="biz-field">卖点 <ElInput v-model="s.point" maxlength="100"/></label><label class="biz-field">价格（元） <ElInputNumber v-model="s.price" :min="0" :precision="2" :step="100"/></label><label class="biz-field">计价单位 <ElSelect v-model="s.unit"><ElOption v-for="x in ['项','次','件']" :key="x" :label="x" :value="x"/></ElSelect></label><label class="biz-field">支付后开始时间 <span class="biz-inline"><ElInputNumber v-model="s.startDays" :min="0"/><ElSelect v-model="s.dayType" style="width:120px"><ElOption label="自然日" value="自然日"/><ElOption label="工作日" value="工作日"/></ElSelect></span></label><label class="biz-field">交付周期（天） <ElInputNumber v-model="s.deliveryDays" :min="1" :max="9999"/></label><label class="biz-field full">交付标准 <ElInput v-model="s.standard" type="textarea" maxlength="500" show-word-limit/></label></div></section></section>
<section v-if="step===4" class="biz-section"><h2>选择提交园区 <b class="required">*</b></h2><ElCheckboxGroup v-model="chosenParks" class="park-select"><ElCheckbox v-for="p in options" :key="p.id" :value="p.id" :label="p.name"/></ElCheckboxGroup><p v-if="errors.parks" class="field-error" role="alert">{{errors.parks}}</p><p v-if="!options.length" class="biz-muted">暂无可提交园区。已上架或审核中的园区不能重复提交。</p><div class="biz-divider"/><div class="biz-inline"><h2 style="margin:0">服务预览</h2><ElButton @click="previewOpen=true">预览详情页</ElButton></div><div class="preview"><ServicePreview :service="form"/></div></section>
<div class="biz-footer"><ElButton :disabled="step===1" @click="step--">上一步</ElButton><ElButton v-if="step<4" type="primary" @click="next">下一步</ElButton><ElButton v-else type="primary" @click="submit">提交审核</ElButton></div>
<ElDialog v-model="previewOpen" title="客户端服务详情预览" width="760px"><ServicePreview :service="form"/></ElDialog><ElDialog v-model="caseOpen" title="新建案例并关联" width="550px"><div class="biz-grid"><label class="biz-field full">案例分类<ElCascader :model-value="inlineCase.category?inlineCase.category.split(' / '):[]" :options="CATEGORY_TREE" filterable clearable @change="inlineCase.category=Array.isArray($event)?$event.join(' / '):''"/></label><label class="biz-field full">标题<ElInput v-model="inlineCase.title" maxlength="60"/></label><label class="biz-field full">介绍<ElInput v-model="inlineCase.intro" type="textarea" maxlength="500"/></label><label class="biz-field full">封面<input type="file" accept="image/*" @change="caseFile"/><small>{{inlineCase.cover}}</small></label></div><template #footer><ElButton @click="caseOpen=false">取消</ElButton><ElButton type="primary" @click="saveInlineCase">保存并关联</ElButton></template></ElDialog></div></template>
<style scoped>.editor{max-width:1040px}.spec-block{border-top:1px solid #e6ebf3;margin-top:18px;padding:18px 0}.spec-block .biz-grid{margin-top:15px}.faq-row{display:flex;gap:8px;margin:10px 0}.park-select{display:grid;gap:8px}.preview{border:1px solid #e1e8f2;border-radius:10px;padding:24px;background:#fff}.preview h3{font-size:21px;margin:8px 0}.preview p{line-height:1.7}.field-error{display:block;color:#bd3f3b;font-size:12px;font-weight:600;margin-top:5px;line-height:1.45}</style>
