<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElButton, ElCascader, ElCheckbox, ElCheckboxGroup, ElDialog, ElInput, ElMessage, ElMessageBox, ElOption, ElSelect, ElTag } from 'element-plus'
import ServicePreview from '@/components/service/ServicePreview.vue'
import { CATEGORY_TREE, money, serviceStatus, STATUS_LABEL, useCommerceStore, type Service } from '@/stores/commerce'
const c=useCommerceStore(),router=useRouter(),route=useRoute();const filter=reactive({park:String(route.query.park||''),category:'',name:''});const applied=reactive({...filter});const tab=ref('all');const page=ref(1);const selected=ref<string[]>([]);const action=ref<'publish'|'offline'>('publish');const dialog=ref(false);const target=ref<Service|null>(null);const detail=ref<Service|null>(null)
const tabs=[['all','全部'],['draft','草稿'],['reviewing','审核中'],['rejected','已驳回'],['on_sale','已上架'],['offline','已下架']]
const filtered=computed(()=>c.data.services.filter(s=>(!applied.category||s.category.startsWith(applied.category))&&(!applied.name||s.name.includes(applied.name))).sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)))
function matches(s:Service,t:string){if(!applied.park)return t==='all'||serviceStatus(s,undefined,c.joinedParks.map(p=>p.id))===t;const own=s.listings[applied.park];if(t==='draft')return !own;if(!own)return false;return t==='all'||own.status===t}
const tabRows=computed(()=>filtered.value.filter(s=>matches(s,tab.value)));const rows=computed(()=>tabRows.value.slice((page.value-1)*20,page.value*20));const count=(t:string)=>filtered.value.filter(s=>matches(s,t)).length
function setTab(t:string){tab.value=t;page.value=1}function query(){Object.assign(applied,filter);page.value=1}function reset(){Object.assign(filter,{park:'',category:'',name:''});tab.value='all';query()}
function create(){if(!c.data.walletOpen){ElMessage.warning('发布服务前请先开通钱包');router.push('/wallet');return}router.push('/service/new')}
function eligible(s:Service,mode:'publish'|'offline'){return c.joinedParks.filter(p=>mode==='publish'? !['on_sale','reviewing'].includes(s.listings[p.id]?.status||'draft'):s.listings[p.id]?.status==='on_sale')}
function operate(s:Service,mode:'publish'|'offline'){target.value=s;action.value=mode;selected.value=[];dialog.value=true}
async function submit(){if(!target.value||!selected.value.length)return;if(action.value==='offline'){try{await ElMessageBox.confirm(`确认将「${target.value.name}」从以下 ${selected.value.length} 个园区下架？下架后该园区不再展示此服务。`,'确认下架',{confirmButtonText:'确认下架',cancelButtonText:'取消',type:'warning'})}catch{return}}c.changeListing(target.value.id,selected.value,action.value==='publish'?'reviewing':'offline');dialog.value=false;ElMessage.success(action.value==='publish'?'已提交园区审核':'服务已下架')}
async function edit(s:Service){if(Object.values(s.listings).some(x=>['on_sale','reviewing'].includes(x.status))){try{await ElMessageBox.confirm('编辑将使已上架或审核中的园区自动下架，保存后需要重新提交审核。','编辑服务',{confirmButtonText:'继续编辑',cancelButtonText:'取消',type:'warning'});c.changeListing(s.id,Object.entries(s.listings).filter(([,x])=>['on_sale','reviewing'].includes(x.status)).map(([id])=>id),'offline')}catch{return}}router.push(`/service/edit/${s.id}`)}
async function remove(s:Service){if(c.data.orders.some(o=>o.serviceId===s.id)){ElMessage.warning('该服务已有订单，不能删除');return}try{await ElMessageBox.confirm(`确认删除「${s.name||'未命名服务'}」？`,'删除服务',{confirmButtonText:'删除',cancelButtonText:'取消',type:'warning'});c.deleteService(s.id);ElMessage.success('服务已删除')}catch{/* cancelled */}}
</script>
<template><div class="biz-page"><header class="biz-head"><div><p class="biz-eyebrow">园区与服务 / 服务管理</p><h1>服务管理</h1><p>按园区查看服务状态，管理发布、上下架与内容。</p></div><ElButton type="primary" @click="create">发布服务</ElButton></header>
<div class="biz-toolbar"><ElSelect v-model="filter.park" clearable placeholder="全部已加入园区"><ElOption v-for="p in c.joinedParks" :key="p.id" :label="p.name" :value="p.id"/></ElSelect><ElCascader :model-value="filter.category?filter.category.split(' / '):[]" :options="CATEGORY_TREE" :props="{checkStrictly:true}" clearable filterable placeholder="全部分类" @change="filter.category=Array.isArray($event)?$event.join(' / '):''"/><ElInput v-model="filter.name" clearable placeholder="搜索服务名称" @keyup.enter="query"/><ElButton type="primary" @click="query">查询</ElButton><ElButton @click="reset">重置</ElButton></div>
<div class="biz-tabs"><button v-for="[key,label] in tabs" :key="key" class="biz-tab" :class="{active:tab===key}" @click="setTab(key)">{{label}} {{count(key)}}</button></div>
<div v-if="!rows.length" class="biz-empty"><h3>{{c.data.services.length?'暂无匹配的服务':'暂无服务，发布第一个服务吧'}}</h3><p>{{c.data.services.length?'请调整筛选条件或清空筛选。':'提交后按园区审核。'}}</p><ElButton v-if="c.data.services.length" @click="reset">清空筛选</ElButton><ElButton v-else type="primary" @click="create">发布服务</ElButton></div><div v-else class="biz-list"><article v-for="s in rows" :key="s.id" class="biz-list-item"><div class="service-line"><div class="service-main"><div class="service-cover" :title="s.cover || '服务封面'">{{s.name?.slice(0,2)||'服务'}}</div><div><span class="biz-muted">{{s.category||'未选择分类'}}</span><h3>{{s.name||'未命名草稿'}}</h3><p>{{s.intro||'尚未填写简介'}}</p></div></div><ElTag :type="serviceStatus(s,undefined,c.joinedParks.map(p=>p.id))==='on_sale'?'success':serviceStatus(s,undefined,c.joinedParks.map(p=>p.id))==='rejected'?'danger':'info'">{{serviceStatus(s,undefined,c.joinedParks.map(p=>p.id))==='draft'?'草稿':STATUS_LABEL[serviceStatus(s,undefined,c.joinedParks.map(p=>p.id)) as keyof typeof STATUS_LABEL]}}</ElTag></div><div class="biz-inline"><span v-for="p in c.joinedParks" :key="p.id" class="park-status" :title="s.listings[p.id]?.reason?`${s.listings[p.id].reason} · ${s.listings[p.id].at.slice(0,19).replace('T',' ')}`:undefined">{{p.name}} · {{s.listings[p.id]?STATUS_LABEL[s.listings[p.id].status]:'未发布'}}<em v-if="s.listings[p.id]?.forced"> · 运营下架</em></span></div><div class="service-bottom"><span class="biz-muted">规格 {{s.specs.length}} 项 · {{money(s.specs[0]?.price||0)}} 起 · 累计销量 {{c.data.orders.filter(o=>o.serviceId===s.id && o.paid>0 && o.status!=='cancelled').length}} · 更新于 {{s.updatedAt.slice(0,10)}}</span><div class="biz-actions"><ElButton text @click="detail=s">详情</ElButton><ElButton text @click="edit(s)">编辑</ElButton><ElButton v-if="eligible(s,'publish').length" text type="primary" @click="operate(s,'publish')">上架</ElButton><ElButton v-if="eligible(s,'offline').length" text @click="operate(s,'offline')">下架</ElButton><ElButton text type="danger" @click="remove(s)">删除</ElButton></div></div></article></div><div v-if="tabRows.length>20" class="biz-footer"><span>共 {{tabRows.length}} 项</span><div class="biz-actions"><ElButton :disabled="page<=1" @click="page--">上一页</ElButton><span>{{page}}</span><ElButton :disabled="page*20>=tabRows.length" @click="page++">下一页</ElButton></div></div>
<ElDialog v-model="dialog" :title="action==='publish'?`上架园区 · ${target?.name||''}`: `下架园区 · ${target?.name||''}`" width="560px"><p class="biz-muted">{{action==='publish'?'选择要上架的园区。已上架或审核中的园区不可重复提交。':'仅可下架已上架园区；审核中的园区不可下架。'}}</p><div class="biz-actions" style="margin:12px 0"><ElButton text @click="selected=target?eligible(target,action).map(p=>p.id):[]">全选可操作</ElButton><ElButton text @click="selected=[]">取消全选</ElButton></div><ElCheckboxGroup v-model="selected" class="park-options"><div v-for="p in c.joinedParks" :key="p.id" class="park-option"><ElCheckbox :value="p.id" :disabled="!target||!eligible(target,action).some(x=>x.id===p.id)">{{p.name}}</ElCheckbox><ElTag :type="target?.listings[p.id]?.status==='on_sale'?'success':target?.listings[p.id]?.status==='rejected'?'danger':'info'">{{target?.listings[p.id]?STATUS_LABEL[target.listings[p.id].status]:'未发布'}}</ElTag><small v-if="target?.listings[p.id]?.reason">{{target.listings[p.id].reason}} · {{target.listings[p.id].at.slice(0,19).replace('T',' ')}}</small></div></ElCheckboxGroup><template #footer><ElButton @click="dialog=false">取消</ElButton><ElButton type="primary" :disabled="!selected.length" @click="submit">{{action==='publish'?'提交上架审核':'下架所选'}}</ElButton></template></ElDialog>
<ElDialog :model-value="Boolean(detail)" @update:model-value="detail=null" title="客户端服务详情预览" width="760px"><ServicePreview v-if="detail" :service="detail"/></ElDialog></div></template>
<style scoped>.service-main{display:flex;gap:15px;align-items:center;min-width:0}.service-cover{width:78px;height:64px;flex:none;display:grid;place-items:center;border-radius:8px;background:#edf3f8;color:#476489;font-size:14px;font-weight:700}.service-line,.service-bottom{display:flex;align-items:flex-start;justify-content:space-between;gap:15px}.service-line p{margin:6px 0 14px}.park-status{font-size:12px;padding:6px 8px;background:#f3f6fb;color:#53647b;border-radius:6px}.park-status em{color:#bb5647;font-style:normal}.service-bottom{align-items:center;margin-top:15px}.park-options{display:grid;gap:8px;margin-top:18px}.park-option{display:grid;grid-template-columns:1fr auto;align-items:center;gap:4px;padding:10px 0;border-bottom:1px solid #edf1f5}.park-option small{grid-column:1/-1;color:#ae5a4c;font-size:12px}</style>
