<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { ElButton, ElCascader, ElDialog, ElInput, ElMessage, ElMessageBox } from 'element-plus'
import { CATEGORY_TREE, clone, useCommerceStore, type Case } from '@/stores/commerce'
const c=useCommerceStore();const filter=reactive({category:'',keyword:''});const applied=reactive({category:'',keyword:''});const visible=ref(false);const form=reactive<Case>({id:'',category:'',title:'',intro:'',cover:'',createdAt:''});const error=ref('')
const rows=computed(()=>c.data.cases.filter(x=>(!applied.category||x.category.includes(applied.category))&&(!applied.keyword||`${x.title}${x.intro}`.includes(applied.keyword))))
function open(item?:Case){Object.assign(form,item?clone(item):{id:crypto.randomUUID(),category:'',title:'',intro:'',cover:'',createdAt:new Date().toISOString()});error.value='';visible.value=true}
function save(){if(!form.category||!form.title.trim()||form.title.length>60||!form.intro.trim()||form.intro.length>500||!form.cover){error.value='请填写完整分类、1–60 字标题、1–500 字介绍并上传封面';return}c.saveCase(form);visible.value=false;ElMessage.success('案例已保存')}
function file(event:Event){const f=(event.target as HTMLInputElement).files?.[0];if(!f)return;if(!f.type.startsWith('image/')||f.size>10*1024*1024){ElMessage.error('封面需为不超过 10MB 的图片');return}form.cover=f.name}
async function remove(item:Case){const links=c.data.services.filter(s=>s.caseIds.includes(item.id)).length;try{await ElMessageBox.confirm(`确认删除「${item.title}」？${links?`该案例已关联 ${links} 项服务，删除后将从服务中移除。`:''}`,'删除案例',{confirmButtonText:'删除',cancelButtonText:'取消',type:'warning'});c.deleteCase(item.id);ElMessage.success('案例已删除')}catch{/* cancelled */}}
</script>
<template><div class="biz-page"><header class="biz-head"><div><p class="biz-eyebrow">店铺管理 / 案例管理</p><h1>案例管理</h1><p>管理店铺案例，可在发布服务时关联。</p></div><ElButton type="primary" @click="open()">新增案例</ElButton></header><div class="biz-toolbar"><ElCascader :model-value="filter.category?filter.category.split(' / '):[]" :options="CATEGORY_TREE" :props="{checkStrictly:true}" clearable filterable placeholder="全部分类" @change="filter.category=Array.isArray($event)?$event.join(' / '):''"/><ElInput v-model="filter.keyword" class="wide" clearable placeholder="搜索标题或介绍" @keyup.enter="Object.assign(applied,filter)"/><ElButton type="primary" @click="Object.assign(applied,filter)">查询</ElButton><ElButton @click="Object.assign(filter,{category:'',keyword:''});Object.assign(applied,filter)">重置</ElButton></div><div v-if="!rows.length" class="biz-empty"><h3>暂无案例</h3><p>添加一个案例，让服务内容更有说服力。</p><ElButton type="primary" @click="open()">新增案例</ElButton></div><div v-else class="biz-list"><article v-for="item in rows" :key="item.id" class="biz-list-item"><p class="biz-muted">{{item.category}}</p><h3>{{item.title}}</h3><p>{{item.intro}}</p><p class="biz-muted">封面：{{item.cover}}</p><footer><ElButton @click="open(item)">编辑</ElButton><ElButton type="danger" plain @click="remove(item)">删除</ElButton></footer></article></div>
<ElDialog v-model="visible" :title="c.data.cases.some(x=>x.id===form.id)?'编辑案例':'新增案例'" width="600px"><div class="biz-grid"><label class="biz-field full">服务分类 <b class="required">*</b><ElCascader :model-value="form.category?form.category.split(' / '):[]" :options="CATEGORY_TREE" clearable filterable placeholder="选择末级分类" @change="form.category=Array.isArray($event)?$event.join(' / '):''"/></label><label class="biz-field full">案例标题 <b class="required">*</b><ElInput v-model="form.title" maxlength="60" show-word-limit/></label><label class="biz-field full">案例介绍 <b class="required">*</b><ElInput v-model="form.intro" type="textarea" :rows="4" maxlength="500" show-word-limit/></label><label class="biz-field full">案例封面 <b class="required">*</b><input type="file" accept="image/*" @change="file"/><small>{{form.cover || '图片 ≤10MB'}}</small></label></div><p v-if="error" class="biz-note danger">{{error}}</p><template #footer><ElButton @click="visible=false">取消</ElButton><ElButton type="primary" @click="save">保存</ElButton></template></ElDialog></div></template>
