<script setup lang="ts">
import { computed,ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElButton,ElDialog,ElMessage,ElMessageBox,ElOption,ElSelect,ElTag } from 'element-plus'
import { dateText,money,useCommerceStore,type Invoice } from '@/stores/commerce'
const c=useCommerceStore(),router=useRouter();const kind=ref<'customer'|'platform'>('customer'),status=ref('');const preview=ref<Invoice|null>(null);const rows=computed(()=>c.data.invoices.filter(i=>i.kind===kind.value&&(!status.value||i.status===status.value)));const labels={issued:'已开票',issuing:'开票中',failed:'开票失败',returned:'已退票',returning:'退票中'}
function download(i:Invoice){const safe=(value:string)=>value.replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]!));const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>演示开票记录</title><style>body{font:16px/1.8 system-ui,sans-serif;max-width:720px;margin:60px auto;color:#243149}h1{font-size:26px}.muted{color:#68778b}dl{display:grid;grid-template-columns:130px 1fr;gap:12px;border-top:1px solid #dce4ef;padding-top:20px}dt{color:#68778b}dd{margin:0}</style><h1>开票记录 · 演示凭证</h1><p class="muted">本文件由本地验收数据生成，并非正式税务发票。</p><dl><dt>记录号</dt><dd>${safe(i.id)}</dd><dt>发票类型</dt><dd>${i.kind==='customer'?'对客发票':'平台服务费发票'}</dd><dt>抬头</dt><dd>${safe(i.title||'—')}</dd><dt>发票号码</dt><dd>${safe(i.number||'待生成')}</dd><dt>金额</dt><dd>${safe(money(i.amount))}</dd><dt>订单</dt><dd>${safe(i.orderIds.join('、'))}</dd><dt>状态</dt><dd>${safe(labels[i.status])}</dd></dl></html>`;const url=URL.createObjectURL(new Blob([html],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`开票记录-${i.id.slice(0,8)}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function returned(id:string){try{await ElMessageBox.confirm('确认退票？对客发票将即时退票，订单可重新开票。平台发票将进入财务退票流程。','退票确认',{confirmButtonText:'确认退票',cancelButtonText:'取消'});c.returnInvoice(id);ElMessage.success('退票申请已处理')}catch{/* cancelled */}}
function retry(id:string){const i=c.data.invoices.find(x=>x.id===id);if(i){i.status='issuing';ElMessage.success('已重新提交开票申请')}}
</script><template><div class="biz-page"><header class="biz-head"><div><p class="biz-eyebrow">发票管理 / 开票记录</p><h1>开票记录</h1><p>查看对客发票与平台服务费发票的开具、退票状态。</p></div><ElButton type="primary" @click="router.push('/invoice/open')">发起开票申请</ElButton></header><div v-if="!c.data.walletOpen" class="biz-empty"><h3>开通钱包后查看开票记录</h3><ElButton type="primary" @click="router.push('/wallet')">前往我的钱包</ElButton></div><template v-else><div class="biz-tabs"><button class="biz-tab" :class="{active:kind==='customer'}" @click="kind='customer'">对客发票</button><button class="biz-tab" :class="{active:kind==='platform'}" @click="kind='platform'">平台服务费发票</button></div><div class="biz-toolbar"><ElSelect v-model="status" clearable placeholder="全部状态"><ElOption v-for="(label,key) in labels" :key="key" :value="key" :label="label"/></ElSelect></div><div v-if="!rows.length" class="biz-empty"><h3>暂无开票记录</h3><p>提交开票申请后可在这里跟踪结果。</p></div><table v-else class="biz-table"><thead><tr><th>记录号 / 订单</th><th>发票抬头 / 号码</th><th>金额</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-for="i in rows" :key="i.id"><td><strong>{{i.id.slice(0,8)}}</strong><br><span class="biz-muted">{{i.orderIds.join('、')}}</span></td><td>{{i.title||i.number||'—'}}</td><td>{{money(i.amount)}}</td><td><ElTag :type="i.status==='issued'?'success':i.status==='failed'?'danger':'info'">{{labels[i.status]}}</ElTag></td><td>{{dateText(i.createdAt)}}</td><td><div class="biz-actions"><ElButton v-if="i.status==='issued'" text type="primary" @click="preview=i">预览</ElButton><ElButton v-if="i.status==='issued'" text @click="download(i)">下载演示凭证</ElButton><ElButton v-if="i.status==='issued'" text @click="returned(i.id)">退票</ElButton><ElButton v-if="i.status==='failed'" text type="primary" @click="retry(i.id)">重试</ElButton></div></td></tr></tbody></table></template><ElDialog :model-value="!!preview" title="开票记录预览" width="560px" @update:model-value="preview=null"><div v-if="preview" class="invoice-preview"><p class="biz-note">本地验收记录，并非正式税务发票。正式文件由开票接口返回。</p><dl><dt>类型</dt><dd>{{preview.kind==='customer'?'对客发票':'平台服务费发票'}}</dd><dt>抬头</dt><dd>{{preview.title||'—'}}</dd><dt>发票号码</dt><dd>{{preview.number||'待生成'}}</dd><dt>金额</dt><dd>{{money(preview.amount)}}</dd><dt>关联订单</dt><dd>{{preview.orderIds.join('、')}}</dd><dt>状态</dt><dd>{{labels[preview.status]}}</dd></dl><ElButton @click="download(preview)">下载演示凭证</ElButton></div></ElDialog></div></template><style scoped>.invoice-preview dl{display:grid;grid-template-columns:92px 1fr;gap:12px;padding:14px 0;margin:0 0 18px}.invoice-preview dt{color:#68778b}.invoice-preview dd{margin:0;overflow-wrap:anywhere}</style>
