<script setup lang="ts">
import { computed, reactive, ref } from 'vue'
import { useRoute,useRouter } from 'vue-router'
import { ElButton,ElCascader,ElInput,ElOption,ElSelect,ElTag } from 'element-plus'
import { CATEGORY_TREE,dateText,money,STATUS_LABEL,useCommerceStore,type OrderStatus } from '@/stores/commerce'
const c=useCommerceStore(),r=useRouter(),route=useRoute();const filter=reactive({park:String(route.query.park||''),category:'',name:'',id:'',from:'',to:''});const applied=reactive({...filter});const tab=ref('all');const page=ref(1);const tabs:[string,string][]=[['all','全部'],['pending_payment','待支付'],['pending_contract','待签约'],['in_service','服务中'],['pending_acceptance','待验收'],['completed','已完成'],['cancelled','已取消']]
const filtered=computed(()=>c.data.walletOpen?c.data.orders.filter(o=>(!applied.park||o.parkId===applied.park)&&(!applied.category||o.category.includes(applied.category))&&(!applied.name||o.serviceName.includes(applied.name))&&(!applied.id||o.id.includes(applied.id))&&(!applied.from||o.createdAt.slice(0,10)>=applied.from)&&(!applied.to||o.createdAt.slice(0,10)<=applied.to)):[]);const rows=computed(()=>filtered.value.filter(o=>tab.value==='all'||o.status===tab.value).slice((page.value-1)*20,page.value*20));const count=(s:string)=>filtered.value.filter(o=>s==='all'||o.status===s).length
function query(){Object.assign(applied,filter);page.value=1}function reset(){Object.assign(filter,{park:'',category:'',name:'',id:'',from:'',to:''});query()}function action(o:{id:string;status:OrderStatus}){if(c.activeRefund(o.id)){r.push({path:'/aftersale',query:{order:o.id}});return}const pane=o.status==='pending_contract'?'contract':o.status==='in_service'?'delivery':o.status==='completed'?'settlement':'bill';r.push({path:`/order/${o.id}`,query:{tab:pane}})}const actionText=(o:{id:string;status:OrderStatus})=>c.activeRefund(o.id)?'处理退款':({pending_payment:'查看订单',pending_contract:'上传合同',in_service:'履约交付',pending_acceptance:'查看验收',completed:'查看评价',cancelled:'查看订单'}[o.status])
</script><template><div class="biz-page"><header class="biz-head"><div><h1>订单管理</h1><p>查看来自已加入园区的订单，按交易阶段处理合同、交付与验收。</p></div></header><div v-if="!c.data.walletOpen" class="biz-empty"><h3>开通钱包后查看订单</h3><p>交易数据将在支付平台开户后解锁。</p><ElButton type="primary" @click="r.push('/wallet')">前往我的钱包</ElButton></div><template v-else><div class="biz-toolbar"><ElSelect v-model="filter.park" clearable placeholder="全部来源园区"><ElOption v-for="p in c.joinedParks" :key="p.id" :value="p.id" :label="p.name"/></ElSelect><ElCascader :model-value="filter.category?filter.category.split(' / '):[]" :options="CATEGORY_TREE" :props="{checkStrictly:true}" clearable filterable placeholder="全部分类" @change="filter.category=Array.isArray($event)?$event.join(' / '):''"/><ElInput v-model="filter.name" placeholder="服务名称" clearable/><ElInput v-model="filter.id" placeholder="订单号" clearable/><label class="date-filter">下单时间 <input v-model="filter.from" type="date"> 至 <input v-model="filter.to" type="date"></label><ElButton type="primary" @click="query">查询</ElButton><ElButton @click="reset">重置</ElButton></div><div class="biz-tabs"><button v-for="[key,label] in tabs" :key="key" class="biz-tab" :class="{active:tab===key}" @click="tab=key;page=1">{{label}} {{count(key)}}</button></div><div v-if="!rows.length" class="biz-empty"><h3>暂无订单</h3><p>符合当前条件的订单会显示在这里。</p></div><table v-else class="biz-table"><thead><tr><th>订单 / 服务</th><th>来源园区</th><th>客户</th><th>实付金额</th><th>状态</th><th>下单时间</th><th>操作</th></tr></thead><tbody><tr v-for="o in rows" :key="o.id"><td><strong>{{o.serviceName}}</strong><br><span class="biz-muted">{{o.id}}</span></td><td>{{c.joinedParks.find(p=>p.id===o.parkId)?.name||'—'}}</td><td>{{o.customer}}</td><td>{{money(o.paid)}}</td><td><ElTag :type="o.status==='completed'?'success':o.status==='cancelled'?'info':'primary'">{{STATUS_LABEL[o.status]}}</ElTag></td><td>{{dateText(o.createdAt)}}</td><td><ElButton text type="primary" @click="action(o)">{{actionText(o)}}</ElButton></td></tr></tbody></table><div v-if="filtered.length>20" class="biz-footer"><span>共 {{filtered.length}} 笔订单</span><div class="biz-actions"><ElButton :disabled="page<=1" @click="page--">上一页</ElButton>{{page}}<ElButton :disabled="page*20>=filtered.length" @click="page++">下一页</ElButton></div></div></template></div></template><style scoped>.date-filter{display:flex;align-items:center;gap:6px;color:#69788d;font-size:12px}.date-filter input{width:125px;height:32px;border:1px solid #d8e1ee;border-radius:7px;padding:0 6px;font:inherit;color:#34465c}</style>
