<script setup lang="ts">
import { reactive } from 'vue'
import { ElButton, ElInput, ElMessage } from 'element-plus'
import { clone, useCommerceStore } from '@/stores/commerce'
const c=useCommerceStore(); const form=reactive(clone(c.data.shop)); const errors=reactive({name:'',intro:''})
function addFiles(event:Event,kind:'logo'|'introImages'|'teamImages') { const files=Array.from((event.target as HTMLInputElement).files||[]); const limit=kind==='logo'?5:10; const valid=files.filter(f=>f.type.startsWith('image/')&&f.size<=limit*1024*1024); if(valid.length!==files.length) ElMessage.error(`仅支持图片，单张不超过 ${limit}MB`); if(kind==='logo') { if(valid[0]) form.logo=valid[0].name } else { const next=[...form[kind],...valid.map(f=>f.name)]; if(next.length>6) ElMessage.warning('最多上传 6 张'); form[kind]=next.slice(0,6) } (event.target as HTMLInputElement).value='' }
function save(){ errors.name=form.name.trim()&&form.name.length<=60?'':'请填写 1–60 字店铺名称'; errors.intro=form.intro.trim()&&form.intro.length<=500?'':'请填写 1–500 字店铺介绍'; if(errors.name||errors.intro)return; c.saveShop(form);ElMessage.success('店铺资料已保存') }
</script>
<template><div class="biz-page"><header class="biz-head"><div><p class="biz-eyebrow">店铺管理 / 店铺资料</p><h1>店铺资料</h1><p>店铺资料将在园区客户端的服务详情中展示。</p></div><ElButton type="primary" @click="save">保存资料</ElButton></header>
<section class="biz-section"><h2>基础资料</h2><div class="biz-grid"><label class="biz-field"><span>店铺 Logo <small>选填 · 图片 ≤5MB</small></span><input type="file" accept="image/*" @change="addFiles($event,'logo')" /><small v-if="form.logo">{{ form.logo }} <a @click="form.logo=''">移除</a></small></label><label class="biz-field" :class="{error:errors.name}"><span>店铺名称 <b class="required">*</b></span><ElInput v-model="form.name" maxlength="60" show-word-limit @input="errors.name=''"/><small v-if="errors.name">{{errors.name}}</small></label><label class="biz-field full" :class="{error:errors.intro}"><span>店铺介绍 <b class="required">*</b></span><ElInput v-model="form.intro" type="textarea" :rows="5" maxlength="500" show-word-limit @input="errors.intro=''"/><small v-if="errors.intro">{{errors.intro}}</small></label></div></section>
<section class="biz-section"><h2>展示图片</h2><div class="biz-grid"><label class="biz-field"><span>店铺简介图片 <small>最多 6 张 · 单张 ≤10MB</small></span><input type="file" multiple accept="image/*" @change="addFiles($event,'introImages')"/><div class="biz-inline"><span v-for="(name,i) in form.introImages" :key="i" class="file-chip">{{name}} <button @click.prevent="form.introImages.splice(i,1)">×</button></span></div></label><label class="biz-field"><span>团队介绍图片 <small>最多 6 张 · 单张 ≤10MB</small></span><input type="file" multiple accept="image/*" @change="addFiles($event,'teamImages')"/><div class="biz-inline"><span v-for="(name,i) in form.teamImages" :key="i" class="file-chip">{{name}} <button @click.prevent="form.teamImages.splice(i,1)">×</button></span></div></label></div></section></div></template>
<style scoped>.file-chip{padding:5px 8px;background:#f1f5fb;border-radius:6px;color:#40516b;font-size:12px}.file-chip button{border:0;background:none;cursor:pointer;color:#9a4c4c}</style>
