<script setup lang="ts">
import { computed } from 'vue'
import { useRouter } from 'vue-router'
import { ElButton, ElTag } from 'element-plus'
import { useProfileStore } from '@/stores/profile'
import { useCommerceStore } from '@/stores/commerce'
import { money } from '@/stores/commerce'
const router=useRouter(),profile=useProfileStore(),c=useCommerceStore()
const pending=computed(()=>c.data.orders.filter(o=>['pending_contract','in_service','pending_acceptance'].includes(o.status)).length)
const score=computed(()=>{const x=c.data.reviews.filter(r=>r.direction==='to_supplier');return x.length?(x.reduce((n,r)=>n+r.score,0)/x.length).toFixed(1):'—'})
const actions=computed(()=>[
  { title:'完善店铺资料',desc:'确认店铺名称、介绍与展示图片',path:'/shop/info',show:!c.data.shop.name||!c.data.shop.intro },
  { title:'开通我的钱包',desc:'开通后可发布服务并使用交易功能',path:'/wallet',show:!c.data.walletOpen },
  { title:'发布第一项服务',desc:'填写服务信息并提交目标园区审核',path:'/service',show:c.data.walletOpen&&!c.data.services.length },
  { title:'处理待签约订单',desc:`${c.data.orders.filter(o=>o.status==='pending_contract').length} 笔订单等待上传或确认合同`,path:'/order',show:c.data.orders.some(o=>o.status==='pending_contract') },
  { title:'处理售后申请',desc:`${c.data.refunds.filter(x=>x.status==='pending').length} 笔待处理退款`,path:'/aftersale',show:c.data.refunds.some(x=>x.status==='pending') },
].filter(x=>x.show))
</script>
<template><div class="biz-page workspace-ready"><header class="biz-head"><div><p class="biz-eyebrow">供应商工作台</p><h1>你好，{{profile.name}}</h1><p>查看当前主体的园区、服务和交易进度。</p></div><ElButton type="primary" @click="router.push('/park')">查看我的园区</ElButton></header><section class="workspace-status"><div><span>当前主体</span><h2>{{c.data.shop.name||'服务商'}}</h2><p>已加入 {{c.joinedParks.length}} 个园区 · {{c.data.services.length}} 项服务</p></div><ElTag type="success">已入驻</ElTag></section><div class="workspace-metrics"><button @click="router.push('/service')"><span>已上架服务</span><strong>{{c.data.services.filter(s=>Object.values(s.listings).some(x=>x.status==='on_sale')).length}}</strong><small>查看服务</small></button><button @click="router.push('/order')"><span>待处理订单</span><strong>{{pending}}</strong><small>查看订单</small></button><button @click="router.push('/invoice/record')"><span>订单实付</span><strong>{{money(c.data.orders.reduce((n,o)=>n+o.paid,0))}}</strong><small>查看交易</small></button><button @click="router.push('/review')"><span>店铺评分</span><strong>{{score}}</strong><small>查看评价</small></button></div><section class="biz-section"><div class="section-heading"><h2>接下来要做</h2><span class="biz-muted">{{actions.length}} 项</span></div><div v-if="!actions.length" class="biz-note">当前暂无待办。你可以继续发布服务，或查看各园区的经营情况。</div><div v-else class="action-list"><button v-for="x in actions" :key="x.title" @click="router.push(x.path)"><span><strong>{{x.title}}</strong><small>{{x.desc}}</small></span><span class="arrow">→</span></button></div></section><section class="biz-section"><h2>常用入口</h2><div class="workspace-links"><ElButton @click="router.push('/shop/info')">店铺资料</ElButton><ElButton @click="router.push('/service')">服务管理</ElButton><ElButton @click="router.push('/order')">订单管理</ElButton><ElButton @click="router.push('/wallet')">我的钱包</ElButton></div></section></div></template>
<style scoped>.workspace-ready{max-width:1120px}.workspace-status{display:flex;justify-content:space-between;align-items:flex-start;gap:16px;border:1px solid #dce8e6;border-radius:12px;background:#f3faf8;padding:23px 25px}.workspace-status span{font-size:12px;color:#547870}.workspace-status h2{font-size:19px;margin:7px 0}.workspace-status p{font-size:13px;color:#647c78;margin:0}.workspace-metrics{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid #e7edf4;margin:20px 0 25px}.workspace-metrics button{padding:22px 12px 22px 4px;text-align:left;background:none;border:0;cursor:pointer;display:grid;gap:6px;border-right:1px solid #edf1f6}.workspace-metrics button:last-child{border:0}.workspace-metrics span{font-size:12px;color:#7b8798}.workspace-metrics strong{font-size:25px;color:#20344f}.workspace-metrics small{color:#3658c4}.section-heading{display:flex;align-items:baseline;gap:8px}.action-list{border-top:1px solid #e7edf4}.action-list button{display:flex;justify-content:space-between;width:100%;padding:16px 0;text-align:left;border:0;border-bottom:1px solid #e7edf4;background:none;cursor:pointer}.action-list strong{display:block;font-size:14px;color:#263a53}.action-list small{display:block;font-size:12px;color:#77869a;margin-top:4px}.arrow{color:#3658c4;font-size:20px}.workspace-links{display:flex;gap:8px;flex-wrap:wrap}@media(max-width:760px){.workspace-metrics{grid-template-columns:repeat(2,1fr)}.workspace-metrics button:nth-child(2){border-right:0}}</style>
